baseURL = "http://jaidevd.com/"
languageCode = "en-us"
title = "Jaidev's Blog"
theme = "noteworthy"

disqusShortname = "brocasbrain"
googleAnalytics = "UA-80129098-1"
paginate = 4

[params]
# Main
math = true
showReadmore = true
description = "Thoughts on data science, statistics and machine learning."
email = "mailto:deshpande.jaidev@gmail.com"
twitter = "https://twitter.com/jaidevd"
youtube = "https://www.youtube.com/playlist?list=PLllKLgiXxcqe3MlAk-6ZrQP82Dr5mgI0d"

# Programming
github = "https://github.com/jaidevd"

[[menu.main]]
	identifier = "about"
	name = "About Me"
	url = "/about/"
	weight = 1
[[menu.main]]
	identifier = "archive"
	name = "Archive"
	url = "/archive/"
	weight = 2

[markup]
	[markup.highlight]
		style = "github"
		codeFences = false
	[markup.goldmark.renderer]
		unsafe = true
[taxonomies]
	tag = "tags"
