description = "Understanding the geometry of OCR bounding boxes; Azure FormRecognizer Layout Analysis"
images = ['gramener.png']
title = "Understanding the geometry of OCR bounding boxes; Azure FormRecognizer Layout Analysis"
